name: Integration Tests

on:
  pull_request:
    branches: [ "trunk", "0.9.x" ]

jobs:
  integration-tests-pr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mysql-version: [ 5.5.62, 5.6.34, 5.6.51, 5.7.10, 5.7.44, 8.0.11, 8.0.36, 8.1.0, 8.2.0 ]
    name: Integration test with MySQL ${{ matrix.mysql-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Temurin 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Integration test with MySQL ${{ matrix.mysql-version }}
        run: |
          set -o pipefail
          ./mvnw -B verify -Dmaven.javadoc.skip=true \
          -Dmaven.surefire.skip=true \
          -Dtest.db.type=mysql \
          -Dtest.db.version=${{ matrix.mysql-version }} \
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN \
          -Dio.netty.leakDetectionLevel=paranoid \
          -Dio.netty.leakDetection.targetRecords=32 \
          | tee test.log
          set +o pipefail
      - name: ensure no leaks
        run: ./.github/scripts/ensure_no_leak.sh test.log
