name: Integration Tests

on:
  pull_request:
    branches: [ "trunk", "0.9.x" ]

jobs:
  integration-tests-pr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        mysql-version: [ 5.5, 5.6, 5.7, 8.0 ]
    name: Integration test with MySQL ${{ matrix.mysql-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Temurin 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Set up MySQL ${{ matrix.mysql-version }}
        uses: asyncer-io/mysql-action@trunk
        with:
          mysql version: ${{ matrix.mysql-version }}
          mysql database: r2dbc
          mysql root password: r2dbc-password!@
      - name: Integration test with MySQL ${{ matrix.mysql-version }}
        run: ./mvnw -B verify -Dmaven.javadoc.skip=true -Dmaven.surefire.skip=true -Dtest.mysql.password=r2dbc-password!@ -Dtest.mysql.version=${{ matrix.mysql-version }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
