name: Unit tests

on:
  pull_request:
    branches: [ "trunk", "0.9.x" ]

jobs:
  unit-tests-pr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
    name: linux-java-${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Unit test with Maven
        run: ./mvnw -B test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN