name: MySQL 8.0

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Temurin 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - name: Shutdown the Default MySQL
        run: sudo service mysql stop
      - name: Set up MySQL 8.0
        uses: asyncerio/mysql-action@v1.1
        with:
          collation server: utf8mb4_0900_ai_ci
          mysql version: 8.0
          mysql database: r2dbc
          mysql root password: ${{ secrets.DB_PASSWORD }}
      - name: Integration test with MySQL 8.0
        run: ./mvnw -B verify -Dmaven.javadoc.skip=true -Dmaven.surefire.skip=true -Dtest.mysql.password=${{ secrets.DB_PASSWORD }} -Dtest.mysql.version=8.0 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
