name: release

on:
  workflow_dispatch:
    inputs:
      Dummy:
        description: Dummy
        required: false
        type: boolean
  pull_request:


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: trunk

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # gh runner local caches lts temurins
          java-version: '8'

      - name: Setup git configs
        run: |
          git config --global user.email "asyncer-io-bot@users.noreply.github.com"
          git config --global user.name "asyncer-io-bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Cache & Reload Local Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-prepare-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-prepare-

      - name: Run release prepare command
        run: |
          ./mvnw -B -ntp --file pom.xml release:prepare -DpreparationGoals=clean -DskipTests=true
          ./mvnw -B -ntp clean
