name: release

on:
  workflow_dispatch:
    inputs:
      Dummy:
        description: Dummy
        required: false
        type: boolean
  pull_request:


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prepare-deploy

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # gh runner local caches lts temurins
          java-version: '8'

      - name: Setup git configs
        run: |
          git config --global user.email "asyncer-io-bot@users.noreply.github.com"
          git config --global user.name "asyncer-io-bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Cache & Reload Local Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-prepare-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-prepare-

      - name: Run release prepare command
        run: |
          ./mvnw -B -ntp --file pom.xml release:prepare -DpreparationGoals=clean -DskipTests=true
          ./mvnw -B -ntp clean

      - name: Ensure Prepared
        run: ./.github/scripts/ensure_prepared.sh

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: prepare-workspace
          path: ${{ github.workspace }}

  stage-release:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: prepare-workspace
          path: ./prepare-workspace/

      - name: fix permissions
        run: chmod 755 ./prepare-workspace/mvnw

      - name: Set up Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # gh runner local caches lts temurins
          java-version: '8'

      - name: Setup git configs
        run: |
          git config --global user.email "asyncer-io-bot@users.noreply.github.com"
          git config --global user.name "asyncer-io-bot"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Cache & Reload Local Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-prepare-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-prepare-

      - name: Set up maven settings
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "ossrh-staging",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            }]

      - name: create local deploy directory
        run: mkdir -p ~/local-staging

      - name: Stage-local-deploy
        run: /bin/bash -cl "cat <(echo -e \"${GPG_PRIVATE_KEY}\") | gpg --batch --import && ./mvnw -B -ntp -am clean javadoc:jar package gpg:sign org.sonatype.plugins:nexus-staging-maven-plugin:deploy -DnexusUrl=https://s01.oss.sonatype.org -DserverId=ossrh-staging -DaltStagingDirectory=/root/local-staging -DskipRemoteStaging=true -DskipTests=true -Dgpg.passphrase=${GPG_PASSPHRASE} -Dgpg.keyname=${GPG_KEYNAME}"

      - name: Rollback Release
        working-directory: ./prepare-workspace/
        if: ${{ failure() }}
        run: ./.github/scripts/release_rollback.sh

